# Generated by Django 4.1.3 on 2022-11-05 10:38

import django.core.validators
from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='The first name can contain only latin letters.', regex='^[A-Za-z]*$')])),
                ('last_name', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='The last name can contain only latin letters.', regex='^[A-Za-z]*$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number format.', regex='^\\+?(38)?\\(?0[1-9]{2}\\)?[0-9]{2}-?[0-9]{3}-?[0-9]{2}$')])),
                ('password', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'users',
            },
            managers=[
                ('objects', user.models.UserManager()),
            ],
        ),
    ]
